services:
  backend:
    build:
      context: ./backend/
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend