services:
  backend:
    build:
      context: ./backend/
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    
  # db:
  #   image: mysql:8.4
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./db:/var/lib/mysql