name: test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: TestBackend
    # create docker compose, run tests, and clean up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout And Build
        run: docker compose -f compose.dev.yml up -d

      - name: Test
        run: docker compose -f compose.dev.yml exec backend go test -v -coverpkg=./... ./...
