name: test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: TestBackend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        run: cd backend
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Run tests
        run: go test ./...
        